### ISSUE TITLE
Findbar not fully hidden when its height is bigger than normal

### ISSUE THREAD

**Issue by TheCatRiX** [RobotoSkunk/zen-better-findbar#3]
![Shown](https://github.com/user-attachments/assets/18d89055-fced-44fc-b4a7-b629ed92f453)
![Hidden](https://github.com/user-attachments/assets/41cd2481-0abf-4e88-9ac2-759c0d2697a6)

**Comment by RobotoSkunk** [comment]
Fixed in 7de240a1239a2214a5a31de9e755a6556b6c8945
